In [1]:
import numpy as np
import pandas as pd

movies=pd.read_csv('../3Datasets/bollywood.csv')
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [2]:
subs=pd.read_csv('../3Datasets/subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [3]:
vk=pd.read_csv('../3Datasets/kohli_ipl.csv')
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [4]:
#astype:- it changes the type of data
import sys
sys.getsizeof(vk)

3604

In [5]:
sys.getsizeof(vk.astype('int16'))

1024

In [ ]:
#between:- {it return boolean series within given range}

vk[vk['runs'].between(51, 99)] #because here vk is a dataframe so, we will apply on specific column

     match_no  runs
33         34    58
40         41    71
43         44    56
44         45    67
51         52    70
56         57    57
67         68    73
70         71    51
72         73    58
73         74    65
79         80    57
80         81    93
81         82    99
84         85    56
96         97    67
98         99    73
102       103    51
103       104    62
109       110    82
115       116    75
116       117    79
118       119    80
121       122    52
126       127    75
128       129    54
130       131    54
131       132    62
133       134    64
136       137    55
140       141    58
143       144    57
144       145    92
147       148    68
151       152    70
159       160    84
161       162    67
174       175    72
177       178    90
187       188    72
196       197    51
197       198    53
208       209    58
212       213    73

In [ ]:
#clip:- yah data ko ek given range me clip kar deta hai.

subs.clip(100,200) #range se bade ya chhote value ko range ke equal kar deta hai

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
#drop_duplicates ->delete either first or last occurrences

temp=pd.Series([1,1,2,2,3,4,5,5,5,6])
temp

0    1
1    1
2    2
3    2
4    3
5    4
6    5
7    5
8    5
9    6
dtype: int64

In [22]:
temp.drop_duplicates(keep='last')

1    1
3    2
4    3
5    4
8    5
9    6
dtype: int64

In [15]:
#To find count of duplicate value
temp.duplicated().sum()

np.int64(4)

In [14]:
#movies par lagane par har actor ki ek hi movie bachegi
movies.drop_duplicates()

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1497 rows x 2 columns]

In [16]:
temp.size

10

In [17]:
temp.count()

np.int64(10)

In [19]:
#isnull -> used to count missing value in the data
temp.isnull().sum()

np.int64(0)

In [23]:
#dropna ->saari missing value ko hatata hai
temp.dropna()

0    1
1    1
2    2
3    2
4    3
5    4
6    5
7    5
8    5
9    6
dtype: int64

In [24]:
#fillna  ->used to fill the value

temp.fillna(0)

0    1
1    1
2    2
3    2
4    3
5    4
6    5
7    5
8    5
9    6
dtype: int64

In [33]:
#isin

vk[vk.isin([49,99])]

     match_no  runs
0         NaN   NaN
1         NaN   NaN
2         NaN   NaN
3         NaN   NaN
4         NaN   NaN
..        ...   ...
210       NaN   NaN
211       NaN   NaN
212       NaN   NaN
213       NaN   NaN
214       NaN   NaN

[215 rows x 2 columns]

In [34]:
#apply:-
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [38]:
movies['lead'].apply(lambda x:x.split()[0].upper())

0         VICKY
1         VICKY
2        ANUPAM
3        EMRAAN
4          MONA
         ...
1495       SHAH
1496    AMITABH
1497      VIVEK
1498       AJAY
1499     AKSHAY
Name: lead, Length: 1500, dtype: str

In [49]:
#copy
new=vk.head()
new

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [51]:
new[1]=5

In [52]:
new

   match_no  runs  1
0         1     1  5
1         2    23  5
2         3    13  5
3         4    12  5
4         5     1  5

In [53]:
next=vk.head().copy()
next[1]=2
next

   match_no  runs  1
0         1     1  2
1         2    23  2
2         3    13  2
3         4    12  2
4         5     1  2